/*----------------------------------------------------------------------------------
Author:         Shahad Naji
Company:        Deloitte
Description:    CMP_Country_Balance controller
Test Class:     CNT_Country_Balance_Test
History
<Date>			<Author>		<Description>
28/11/2019		Shahad Naji     Initial version
----------------------------------------------------------------------------------*/
public class CNT_PaymentTrackingItem {
    
/*----------------------------------------------------------------------------------
Author:         Shahad Naji
Company:        Deloitte
Description:    Returns the name of a country 
History
<Date>			<Author>		<Description>
28/11/2019		Shahad Naji     Initial version
----------------------------------------------------------------------------------
    @AuraEnabled
    public static String getCountryName(String ISOCode){
        String str = '';
        str = Global_Utilities.getCountryName(ISOCode);
        return str;
    }*/
    
}