/*----------------------------------------------------------------------------------
Author:        R. Cervino
Company:        Deloitte
Description:    Global class to be to trhow custom exceptions
Test Class:     CustomException_Test
History
<Date>			<Author>		<Description>
01/04/2020		R. Alexander Cervino     Initial version
----------------------------------------------------------------------------------*/
public class CNT_LoginVisibilityManagerControllerTest {
    /*
     @isTest
    public static void getUserSerializedJwtTokenTest(){
        user u =DataFactory.getRunningUser(true);
        System.runAs(u){
        	Global_IntegrationWrapper.getUserSerializedJwtToken('','https://e-onetrade-dev.de-c1.cloudhub.io/api/v1/nx/inicio','GET');
            Global_IntegrationWrapper.getUserSerializedJwtToken('','https://e-onetrade-dev.de-c1.cloudhub.io/api/v1/nx/inicio','POST');
        }
    }*/

}