/*----------------------------------------------------------------------------------
Author:         R. Alexander Cervino
Company:        Deloitte
Description:    Wrapper class to retrieve and give format to the swift payments
Test Class:     WRAPPER_BackFrontPain002_Test
History
<Date>			<Author>		<Description>
23/01/2020		R. Alexander Cervino     Initial version
----------------------------------------------------------------------------------*/
public with sharing class WRAPPER_BackFrontPain002Search{
/*
    private String output;
    private String input;

    public String getOutput () {
        return this.output;
    }

    public WRAPPER_BackFrontPain002Search(String filters){
        this.input=filters;
    }*/

    /*----------------------------------------------------------------------------------
    Author:         R. Alexander Cervino
    Company:        Deloitte
    Description:    Method that retrieves the data from the input source
    History
    <Date>			<Author>		<Description>
23/01/2020		R. Alexander Cervino     Initial version
    ---------------------------------------------------------------------------------
    public void execute(){
        try {
            String response='["Santander Brazil S.L.","Deloitte S.L.U","China Market S.A.","HP Entreprise S.A.","Santander Tech S.A."]';
            this.output = null;*/
            
            /*if(input!='' && input!='undefined' && input!=null && input=='status=Rejected'){
                response = Global_IntegrationWrapper.launchHttp('','https://e-onetrade.de-c1.cloudhub.io/api/payments_tracker?'+input,'GET');
            }else{
                response = Global_IntegrationWrapper.launchHttp('','https://e-onetrade.de-c1.cloudhub.io/api/payments_tracker','GET');
            }

            if (String.isNotBlank(response)) {
                this.output = response;
            } else {
                //FALTA LA LABEL
                throw new customException('Error al consultar los datos');
            }
        } catch (Exception e) {
            System.debug('execute.CNT_WRAPPERSWIFTPAYMENT: ' + e.getMessage());
			throw new customException(e.getMessage());
        }
    }*/
}